### ISSUE TITLE
Définition des params de peersim dans le fichier de scénario

### ISSUE THREAD

**Issue by n-peugnet** [PolyProcessInterface/ppi#33]
Je pense qu'un bon endroit pour définir la seed et les autres paramètres de peersim serait le fichier de scénario.

Je verrais bien un truc comme ça (dépends de #31) :

```json
{
	"peersimFile": "testpeersim.conf",
	"events": [
		...
	],
	"failures": [
		...
	]
}
```

Du coup il faudrait enlever le plus possible de lignes de notre `peersim.base.conf` pour laisser l'utilisateur paramètrer peersim. En gros il ne faudrait quasiment garder que ça dans le `peersim.base.conf`:
```
protocol.infra org.sar.ppi.peersim.PeerSimInfrastructure
protocol.infra.transport transport

init.i org.sar.ppi.peersim.PeerSimInit
init.i.infrapid infra
```

**Comment by Atlaoui** [comment]
ok plus le path  vers le .json car je vois pas comment ne pas le mettre dans le fichier de conf
